version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
        - data:/data/db
    env_file:
        - ./.env
    networks:
      - mern-ecommerce        
  backend:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - logs:/app/logs
      - .:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - mongodb
    networks:
      - mern-ecommerce

networks:
  mern-ecommerce:
    driver: bridge
    external: false
    name: mern-ecommerce

volumes:
  data:
  logs:

